language: c
cache: ccache
matrix:
# gcc
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      env:
        - secure: "OIN5iLSZBgBIyRUFuxVjgMZEDv30y5XTxaP8DjmzommL949f3M3rcPNabvtjH8ehR7By1OpBQVKP2u52KJJJSw8PC4zRh4ddqgyvXT5fP5uiV5oepOBHpWMdHWCAND9c0RF5tK4lj8rs9E5lll9C01qlCQOP6Vq8az6d+K54R3eEWiDZh03qWBzKyhoPdUMlDHCnMTZF4DKVD1uaUmHfOL4nj+gohH3j4DoTCt0ItwaR/6uKo3Lpexq3Ho/xJk//lDXBb1IHvxBnmtpU/nRRMop8SkZyy6UzZFssCTjul0rH1rEbadI8hbOoj2UCfGdGRqT3fiyUxghBcU5K4WdXtJIk5iOeiJ0aSZ/X5TOTWcBBfV9htIp9w7apHaNPwlq0EQfti81hGDtOTzYqjVjzqO1FxaZF7Oa8HTS68bp2YXug1cXoFr9m2TaoS3nTDsQFh0t0UOERiC0voIxh+QYizzrTr818LxJrxHTd1qVIJkym+HaUDms9FJ6saMxICXp3tBqrwfvwGs5+jUJcSu+3TrqB9XOLjAuXyfx56sXH+ojZICasocVaEHmgWN5ZuNCJvYso6Q8WzQ1ZH8N5ra7Pfi1GPlwdMUfQ4r/4SWSOqg9G8/iMBzvEq9nDieKRzcsnYhIREW2ST3MB7Wm37BQE5h1KAt5zpzqO+7DyDvN3wuM="
      before_install:
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      addons:
        coverity_scan:
          project:
            name: "theimpossibleastronaut/modemu2k"
            description: "modemu2k is a fork of modemu, a telnet client with a modem-like user interface"
          notification_email: "andy400-dev@yahoo.com"
          build_command_prepend: "./configure"
          build_command: "make"
          branch_pattern: coverity_scan

