name: AppImage Build

on:
  push:
    tags:
      - v**

jobs:

  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    # Runs a single command using the runners shell
    - name: Install required dependencies
      run: |
        sudo apt-get install -y gettext
        sudo apt-get install -y python3-pip python3-setuptools
        sudo -H python3 -m pip install meson ninja

    # Runs a set of commands using the runners shell
    - name: Download building tools & executing AppImage build
      run: |
        wget -nv -c https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        chmod +x linuxdeploy-x86_64.AppImage
    - run: |
        meson setup _build -Dprefix=/usr -Dstrip=true --buildtype=release
        cd _build
        ninja
        DESTDIR=$PWD/AppDir ninja -v install
        ../linuxdeploy-x86_64.AppImage --executable AppDir/usr/bin/modemu2k \
          --icon-file=../packaging/modemu2k.png --icon-filename=modemu2k \
          --create-desktop-file --appdir $PWD/AppDir --output appimage
    - name: Deploy AppImage
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: True
        prerelease: False
        name: modemu2k ${GITHUB_REF}
        artifacts: "_build/modemu2k*AppImage"
        token: ${{ secrets.GITHUB_TOKEN }}
        omitNameDuringUpdate: True
        omitBodyDuringUpdate: True
