name: C/C++ CI
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: master
    paths-ignore:
    - '**/*.md'
  pull_request:
    branches: master
    paths-ignore:
    - '**/*.md'

jobs:
  gcc:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      MATRIX_OS: ${{ matrix.os }}
      MATRIX_ARCH: ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v2
    - run: sh ./.github/scripts/test_m2k.sh

  clang:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os: [ubuntu-latest]
        compiler: [clang]
    runs-on: ${{ matrix.os }}
    env:
      MAXTRIX_OS: ${{ matrix.os }}
      MAXTRIX_ARCH: ${{ matrix.arch }}
    steps:
    - uses: actions/checkout@v2
    - run: sh ./.github/scripts/test_m2k.sh


  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install meson
    - run: |
        meson builddir
        cd builddir
        ninja -v
        ninja test
        # ninja -C builddir dist
